on: push

name: Run
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0']
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
    - name: Run composer install
      run: composer install -n --prefer-dist
      env:
        APP_ENV: testing
    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate
    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.lock') }}
    - name: Run insights
      run: php artisan insights --no-interaction --min-quality=90 --min-complexity=85 --min-architecture=90 --min-style=95
    - name: Run tests
      run: php artisan test --parallel
      env:
        APP_ENV: testing
    - name: Run php-cs-fixer
      run: ./vendor/bin/php-cs-fixer fix
    - name: Commit php cs fixes
      uses: stefanzweifel/git-auto-commit-action@v4
      id: commit
      with:
        commit_message: 'phpcs fixes'
